server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # BARIS PALING KRUSIAL UNTUK REACT ROUTER:
        # Jika file/page tidak ditemukan, arahkan semuanya kembali ke index.html
        try_files $uri $uri/ /index.html;
    }

    # Mengaktifkan Gzip Compression agar aset JS/CSS dikirim lebih cepat & hemat bandwidth
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Handle error halaman dari sisi server
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}